apiVersion: v1
kind: Service
metadata:
  name: gpt2-text-generator-service
spec:
  selector:
    app: gpt2-text-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
